<template>
    <div id="educationModal" class="modal fade" role="dialog">
	<div class="modal-dialog modal-lg">

	    <!-- Modal content-->
	    <div class="modal-content box-edge">
	    	<div class="modal-head">
	    		<div class="border-bot" style="padding:16px 0;">
	    			<h6 class="reset c-dark">Education Information</h6>
	    		</div>
	    	</div>   	
			<div class="modal-body" style="padding-top:0;overflow:hidden">
				<ul class="p-infolist">
					<li class="border-bot" style="width:100%;margin-top:10px;">
						<h6 class="f-11 c-dark mb-10 pull-left c-green bold">Elementary</h6>
						<i class="fa fa-chevron-down pull-right c-green mt-5"></i>
					</li>
					<li>
						<ul>
							<li>
								<h6 class="f-11 c-light mb-3">School Name</h6>
								<input type="text" style="width:645px;">
							</li>
							<li>
								<h6 class="f-11 c-light mb-3">Academic Year</h6>
								<input type="text" style="width:150px;">
							</li>
							<li style="margin-right:0;">
								<h6 class="f-11 c-light mb-3">Honor</h6>
								<input type="text" style="width:150px;">
							</li>
						</ul>
					</li>
					<li class="border-bot" style="width:100%">
					<h6 class="f-11 c-dark mb-10">Address</h6>
				</li>
				<li>
					<ul>
						<li>
							<h6 class="f-11 c-light mb-3">Province</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">City</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Barangay</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Blk no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Lot no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Zip code</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Street</h6>
							<input type="text" style="width:150px;">
						</li>
						<li style="margin-right:0;">
							<h6 class="f-11 c-light mb-3">Country</h6>
							<select name="" id="">
								<option value="Unites States of America">United States</option>
								<option value="Philippines">Philippines</option>
							</select>
						</li>
					</ul>
				</li>

				<li class="border-bot" style="width:100%;margin-top:10px;">
						<h6 class="f-11 c-dark mb-10 pull-left c-green bold">Junior High</h6>
						<i class="fa fa-chevron-down pull-right c-green mt-5"></i>
					</li>
					<li>
						<ul>
							<li>
								<h6 class="f-11 c-light mb-3">School Name</h6>
								<input type="text" style="width:645px;">
							</li>
							<li>
								<h6 class="f-11 c-light mb-3">Academic Year</h6>
								<input type="text" style="width:150px;">
							</li>
							<li style="margin-right:0;">
								<h6 class="f-11 c-light mb-3">Honor</h6>
								<input type="text" style="width:150px;">
							</li>
						</ul>
					</li>
					<li class="border-bot" style="width:100%">
					<h6 class="f-11 c-dark mb-10">Address</h6>
				</li>
				<li>
					<ul>
						<li>
							<h6 class="f-11 c-light mb-3">Province</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">City</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Barangay</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Blk no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Lot no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Zip code</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Street</h6>
							<input type="text" style="width:150px;">
						</li>
						<li style="margin-right:0;">
							<h6 class="f-11 c-light mb-3">Country</h6>
							<select name="" id="">
								<option value="Unites States of America">United States</option>
								<option value="Philippines">Philippines</option>
							</select>
						</li>
					</ul>
				</li>

				<li class="border-bot" style="width:100%;margin-top:10px;">
					<h6 class="f-11 c-dark mb-10 pull-left c-green bold">Senior High</h6>
					<i class="fa fa-chevron-down pull-right c-green mt-5"></i>
				</li>
				<li style="margin-bottom:0">
					<ul>
						<li>
							<h6 class="f-11 c-light mb-3">School Name</h6>
							<input type="text" style="width:645px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Academic Year</h6>
							<input type="text" style="width:150px;">
						</li>
						<li style="margin-right:0;">
							<h6 class="f-11 c-light mb-3">Honor</h6>
							<input type="text" style="width:150px;">
						</li>
					</ul>
				</li>
				<li style="width:100%">
					<h6 class="f-11 c-light mb-3">program</h6>
					<input type="text" style="width:100%;">
				</li>
				<li class="border-bot" style="width:100%">
					<h6 class="f-11 c-dark mb-10">Address</h6>
				</li>
				<li>
					<ul>
						<li>
							<h6 class="f-11 c-light mb-3">Province</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">City</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Barangay</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Blk no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Lot no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Zip code</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Street</h6>
							<input type="text" style="width:150px;">
						</li>
						<li style="margin-right:0;">
							<h6 class="f-11 c-light mb-3">Country</h6>
							<select name="" id="">
								<option value="Unites States of America">United States</option>
								<option value="Philippines">Philippines</option>
							</select>
						</li>
					</ul>
				</li>

				<li class="border-bot" style="width:100%;margin-top:10px;">
					<h6 class="f-11 c-dark mb-10 pull-left c-green bold">College</h6>
					<i class="fa fa-chevron-down pull-right c-green mt-5"></i>
				</li>
					<li style="margin-bottom:0">
						<ul>
							<li>
								<h6 class="f-11 c-light mb-3">School Name</h6>
								<input type="text" style="width:645px;">
							</li>
							<li>
								<h6 class="f-11 c-light mb-3">Academic Year</h6>
								<input type="text" style="width:150px;">
							</li>
							<li style="margin-right:0;">
								<h6 class="f-11 c-light mb-3">Honor</h6>
								<input type="text" style="width:150px;">
							</li>
						</ul>
					</li>
				<li style="width:100%">
					<h6 class="f-11 c-light mb-3">program</h6>
					<input type="text" style="width:100%;">
				</li>
				<li class="border-bot" style="width:100%">
					<h6 class="f-11 c-dark mb-10">Address</h6>
				</li>
				<li>
					<ul>
						<li>
							<h6 class="f-11 c-light mb-3">Province</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">City</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Barangay</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Blk no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Lot no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Zip code</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Street</h6>
							<input type="text" style="width:150px;">
						</li>
						<li style="margin-right:0;">
							<h6 class="f-11 c-light mb-3">Country</h6>
							<select name="" id="">
								<option value="Unites States of America">United States</option>
								<option value="Philippines">Philippines</option>
							</select>
						</li>
					</ul>
				</li>

				<li class="border-bot" style="width:100%;margin-top:10px;">
					<h6 class="f-11 c-dark mb-10 pull-left c-green bold">Masters</h6>
					<i class="fa fa-chevron-down pull-right c-green mt-5"></i>
				</li>
					<li style="margin-bottom:0">
						<ul>
							<li>
								<h6 class="f-11 c-light mb-3">School Name</h6>
								<input type="text" style="width:645px;">
							</li>
							<li>
								<h6 class="f-11 c-light mb-3">Academic Year</h6>
								<input type="text" style="width:150px;">
							</li>
							<li style="margin-right:0;">
								<h6 class="f-11 c-light mb-3">Honor</h6>
								<input type="text" style="width:150px;">
							</li>
						</ul>
					</li>
				<li style="width:100%">
					<h6 class="f-11 c-light mb-3">program</h6>
					<input type="text" style="width:100%;">
				</li>
				<li class="border-bot" style="width:100%">
					<h6 class="f-11 c-dark mb-10">Address</h6>
				</li>
				<li>
					<ul>
						<li>
							<h6 class="f-11 c-light mb-3">Province</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">City</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Barangay</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Blk no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Lot no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Zip code</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Street</h6>
							<input type="text" style="width:150px;">
						</li>
						<li style="margin-right:0;">
							<h6 class="f-11 c-light mb-3">Country</h6>
							<select name="" id="">
								<option value="Unites States of America">United States</option>
								<option value="Philippines">Philippines</option>
							</select>
						</li>
					</ul>
				</li>

				<li class="border-bot" style="width:100%;margin-top:10px;">
					<h6 class="f-11 c-dark mb-10 pull-left c-green bold">Doctorate</h6>
					<i class="fa fa-chevron-down pull-right c-green mt-5"></i>
				</li>
					<li style="margin-bottom:0">
						<ul>
							<li>
								<h6 class="f-11 c-light mb-3">School Name</h6>
								<input type="text" style="width:645px;">
							</li>
							<li>
								<h6 class="f-11 c-light mb-3">Academic Year</h6>
								<input type="text" style="width:150px;">
							</li>
							<li style="margin-right:0;">
								<h6 class="f-11 c-light mb-3">Honor</h6>
								<input type="text" style="width:150px;">
							</li>
						</ul>
					</li>
				<li style="width:100%">
					<h6 class="f-11 c-light mb-3">program</h6>
					<input type="text" style="width:100%;">
				</li>
				<li class="border-bot" style="width:100%">
					<h6 class="f-11 c-dark mb-10">Address</h6>
				</li>
				<li>
					<ul>
						<li>
							<h6 class="f-11 c-light mb-3">Province</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">City</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Barangay</h6>
							<input type="text" style="width:150px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Blk no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Lot no.</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Zip code</h6>
							<input type="text" style="width:50px;">
						</li>
						<li>
							<h6 class="f-11 c-light mb-3">Street</h6>
							<input type="text" style="width:150px;">
						</li>
						<li style="margin-right:0;">
							<h6 class="f-11 c-light mb-3">Country</h6>
							<select name="" id="">
								<option value="Unites States of America">United States</option>
								<option value="Philippines">Philippines</option>
							</select>
						</li>
					</ul>
				</li>
				</ul>
				<button class="btn btn-success btn-prime btn-sm pull-right" style="padding:5px 25px;margin:15px 0;">Save</button>
			</div>
	  	</div>
	</div>
</div>
</template>


<script>
export default {
    props:['url', 'data'],

    data(){
        return {
			
        }
    },

    methods: {
        fetchEdu:function(){
            
        }
    }
}
</script>
